language: node_js
node_js:
  - "10"
before_install:
- npm install
script:
- npm run build
- npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8